FROM ubuntu:14.04

MAINTAINER Congying <congying1112@gmail.com>



RUN export HTTP_PROXY=http://brushbrush10.cloudapp.net:12345
RUN export HTTPS_PROXY=http://brushbrush10.cloudapp.net:12345
RUN export http_proxy=http://brushbrush10.cloudapp.net:12345
RUN export https_proxy=http://brushbrush10.cloudapp.net:12345

RUN apt-get update && apt-get -y upgrade
